#!/usr/bin/env bash
# does the display of "Best School" 10 times and a "Hi" on the 9th using a while loop

x=0

while [ $x -lt 10 ]
do
  echo "Best School"
  if [[ "$x" == 8 ]]; then
    echo "Hi"
  fi
  ((x++))
done

