#!/usr/bin/env bash
# a Bash script that displays the time for 12 hours and 59 minutes:
#   displays hours from 0 to 12
#   displays minutes from 1 to 59

x=0

while [ $x -le 12 ]
do
  echo "Hour: $x"

  y=1

  while [ $y -le 59 ]
  do
    echo "$y"
    ((y++))
  done
  ((x++))
done
